spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/communikey?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true&autoReconnect=true
    username:
    password:
    data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      indent_output: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always

logging:
  config: classpath:log4j2-dev.yml
