spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      indent_output: false
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
