application:
  version: 0.3.0

spring:
  application:
    name: communikey
  jackson:
    serialization:
      write_dates_as_timestamps: false
  mvc:
    favicon:
      enabled: false

communikey:
  security:
    root:
      login: root
      email: cckey_root@communicode.de
      password: password
      public-key: |
                -----BEGIN PUBLIC KEY-----
                THIS IS AN EXAMPLE KEY !!!
                -----END PUBLIC KEY-----

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json
