spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      indent_output: true
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  output:
    ansi:
      enabled: always

logging:
  config: classpath:log4j2-dev.yml
